# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Location_name',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='photo',
        ),
    ]
